/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kostroman (https://sketchfab.com/Kostroman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/motion-sensor-83336bbce3a04aeeb565f1969040304f
Title: Motion sensor
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Sensor = (props) => {
    const { nodes, materials } = useGLTF('/models/sensor/sensor.gltf');
    const sensorRef = useRef(); // Reference for the entire sensor group

    // Add rotation animation using useFrame
    useFrame(() => {
        if (sensorRef.current) {
            sensorRef.current.rotation.y += 0.02; // Rotate on Y-axis
        }
    });

    return (
        <group ref={sensorRef} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, 31.7441, -16.598]} scale={1.3}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial.geometry}
                            material={materials.Body_box}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_1.geometry}
                            material={materials.Body_box}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_2.geometry}
                            material={materials.Body_box}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_3.geometry}
                            material={materials.Body_box}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_4.geometry}
                            material={materials.Body_box}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_5.geometry}
                            material={materials.Body_box}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_6.geometry}
                            material={materials.Led_ring}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
};

useGLTF.preload('/models/sensors/sensor.gltf');
export default Sensor;
