/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: michael.evan.allison (https://sketchfab.com/michael.evan.allison)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/security-station-bb05203ac00b4ccc94e9230fdf7c37c0
Title: Security Station
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Something = (props)=> {
    const { nodes, materials } = useGLTF('/models/scene.gltf')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.Material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials['Material.003']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_8.geometry}
                material={materials['Material.004']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_10.geometry}
                material={materials['Material.001']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_12.geometry}
                material={materials['Material.003']}
                position={[0, -0.65, 0]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials['Material.004']}
                position={[0, -0.65, 0]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials['Material.001']}
                position={[0, 0, 0.005]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18.geometry}
                material={materials['Material.001']}
                position={[0, 0, -0.006]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials['Material.004']}
                position={[0, -0.39, 1.01]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials['Material.004']}
                position={[-1.09, -0.4, -0.09]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_24.geometry}
                material={materials['Material.004']}
                position={[0.99, -0.4, -0.09]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_26.geometry}
                material={materials['Material.004']}
                position={[-0.19, -0.39, -1.09]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_28.geometry}
                material={materials['Material.001']}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
        </group>
    )
}

useGLTF.preload('/models/scene.gltf')
export default Something;